[package]
name = "rxed"
version = "0.1.0"
authors = ["TA Thanh Dinh <tathanhdinh@gmail.com>"]

build = "build.rs"

[lib]
crate-type = ["staticlib"]

[dependencies]
failure = "*"
failure_derive = "*"

[build-dependencies]
bindgen = "*"

